project:
  type: website
  output-dir: docs

website:
  title: "My blog"
  description: "Ideas, projects and experiments"
  navbar:
    right:
      - href: publications.qmd
        text: Publications
      - href: posts/index.qmd
        text: Posts
      - href: notes/index.qmd
        text: Notes
    search: true

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    toc-depth: 2

metadata-files:
  - _metadata.yml
